services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pdf_vector_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: Javadb
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: resource_engine
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: